# Server Port Configuration
server.port=8081

# Database Configuration (merchant_db)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/merchant_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Application Name
spring.application.name=merchant-service-java

# Consul Discovery Configuration
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=spring-cloud-merchant-service
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.query-passing=true

# Target Rust Payment Service Endpoint for Outbox Sync via Consul Discovery Service Name
payment.service.rust.url=http://axum-payment-service/api/internal/sync-merchant

# Scheduling & Async Task Execution
spring.main.allow-bean-definition-overriding=true
spring.task.scheduling.pool.size=2
spring.task.execution.pool.core-size=5
